language: node_js

matrix:
  fast_finish: true
  include:
  - node_js: stable
  - node_js: 6
  - node_js: 7
  - node_js: 8
  - node_js: 9
  - node_js: 10
  - node_js: 11
  allow_failures:
  - node_js: 6
  - node_js: 7
  - node_js: 8
  - node_js: 9
  - node_js: 10
  - node_js: 11

before_script: 
  - npm update
  - npm audit fix

after_success: npm run coverage

before_deploy:
  - npm --no-git-tag-version version 1.0.$TRAVIS_BUILD_NUMBER
  - npm run build

deploy:
  provider: npm
  email: chris@cns.me.uk
  api_key:
    secure: B5shnmOZEKZmRK/cLcinKirXFybw8ViUH0tkUBjcYzrlbfvMejE3UMqx9Zb2iQaAoGpdhwveiMPknKWZIBHNxDdq7Eym0K5X7xWPzYRc2tEfKrmZeqpQMmAF221npHOpHorWG1xlw9D61Jae/QIbQ1pOGKTdaLotWXO/mblI0Rvm+weCLWkI7N8EqhG0CuM9jg0QrbYLTnZmUH+FJLXKwrPgOGVOSjZr+iGSWbBZjEaAkeu+31jBS/zH2kZRTbyduFb+EQK13/VahO3wZKVga+vODj+5E4S1hAP6PZESXt1WehdPoIgWb3fqYESZrFfjCJm9sU9WExb0b5lfLA3fcxktatgH3yKWs53vZV3aTiwrcb4g0yKpQSH/Xt7KP6sRrUQiWKcXNnv7iqV1sXZuNfvJ9Z3Nm6vfqJ2nTRHnJXj06DlXzXiC99GQ7kC2UFztLa0+sqXkDnjBASXI7n7VpWzqXtXD8Bt+4WaL88WvsPqSRGfosi63NiXFP2wTR1WRK0VsShRf7ROl+y3lNnVEmINRfNnoYeQkqUrg6RHgGZVpkP/RCwANXx0KsAujuaOUq6DfeF6MdaLt5pwIpSFQsG5OXs1jhQ4nxzJ5H5i/TE220GQWdV2EfXB6dfaUQCEDeyhFalsryhdnl88dvPbkkBbmc+8FF28byxELEntu1mI=
  skip_cleanup: true
  on:
    branch: master
    node_js: stable
